from rag import NEWS_DATA, get_relevant_data, query_news
from utils import generate_with_single_input, pprint


def format_relevant_data(relevant_data):
    """
    Formats a list of relevant documents into a structured string for use in a RAG system.

    Parameters:
    relevant_data (list): A list with relevant data.

    Returns:
    str: A formatted string with the relevant documents, structured for use in a Retrieval-Augmented Generation (RAG) system.
    """
    formatted_documents = []

    for document in relevant_data:
        formatted_document = f"Title: {document['title']}, Description: {document['description']}, Published at: {document['published_at']}\nURL: {document['url']}"
        formatted_documents.append(formatted_document)

    return "\n".join(formatted_documents)


def generate_final_prompt(query, top_k=5, use_rag=True, prompt=None):
    """
    Generates a final prompt based on a user query, optionally incorporating relevant data using retrieval-augmented generation (RAG).

    Args:
        query (str): The user query for which the prompt is to be generated.
        top_k (int, optional): The number of top relevant data pieces to retrieve and incorporate. Default is 5.
        use_rag (bool, optional): A flag indicating whether to use retrieval-augmented generation (RAG)
                                  by including relevant data in the prompt. Default is True.
        prompt (str, optional): A template string for the prompt. It can contain placeholders {query} and {documents}
                                for formatting with the query and formatted relevant data, respectively.

    Returns:
        str: The generated prompt, either consisting solely of the query or expanded with relevant data
             formatted for additional context.
    """
    if not use_rag:
        return query

    relevant_data = get_relevant_data(query, top_k=top_k)
    retrieve_data_formatted = format_relevant_data(relevant_data)

    if prompt is None:
        prompt = (
            f"Answer the user query below. There will be provided additional information for you to compose your answer. "
            f"The relevant information provided is from 2024 and it should be added as your overall knowledge to answer the query, "
            f"you should not rely only on this information to answer the query, but add it to your overall knowledge."
            f"Query: {query}\n"
            f"2024 News: {retrieve_data_formatted}"
        )
    else:
        prompt = prompt.format(query=query, documents=retrieve_data_formatted)

    return prompt


def llm_call(query, top_k=5, use_rag=True, prompt=None):
    """
    Calls the LLM to generate a response based on a query, optionally using retrieval-augmented generation.

    Args:
        query (str): The user query that will be processed by the language model.
        use_rag (bool, optional): A flag that indicates whether to use retrieval-augmented generation by
                                  incorporating relevant documents into the prompt. Default is True.

    Returns:
        str: The content of the response generated by the language model.
    """
    prompt = generate_final_prompt(query, top_k, use_rag, prompt)
    generated_response = generate_with_single_input(prompt)
    generated_message = generated_response['content']

    return generated_message


if __name__ == "__main__":
    pprint(NEWS_DATA[9:11])
    pprint(query_news([3, 6, 9]))

    example_data = NEWS_DATA[4:8]
    print(format_relevant_data(example_data))

    print("\n" + "=" * 55)
    print("          Interactive RAG Terminal Prompt")
    print("         (Type 'exit' or 'q' to quit)")
    print("=" * 55)

    while True:
        try:
            query = input("\nEnter your query: ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExiting.")
            break

        if not query:
            continue
        if query.lower() in ("exit", "quit", "q"):
            print("Goodbye!")
            break

        print("\n--- Generating Response WITH RAG ---")
        response_rag = llm_call(query, use_rag=True)
        print(response_rag)

        print("\n--- Generating Response WITHOUT RAG ---")
        response_no_rag = llm_call(query, use_rag=False)
        print(response_no_rag)